@startuml

card Server {
    card 连接管理器 {
        card 连接1 {
            card Session1 {
                card 临时服务容器1
            }
        }
        card 连接2 {
            card Session2 {
                card 临时服务容器2
            }
        }
    }

    card 数据转换 {
        card 序列化
        card 反列化
    }

    card 检查项 {
        card 连接检查项 {

        }
    }

}

@enduml